# Generated by Django 3.0.3 on 2020-05-31 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0004_auto_20200531_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Myapp.Session'),
        ),
    ]
